/**
 * Flat OpenDocument Text (.fodt) generation for draft reports.
 * All interpolated text is XML-escaped; each source line becomes one text:p.
 */

export function xmlEscape(text) {
  return String(text ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function paragraphs(text, styleName) {
  const style = styleName ? ` text:style-name="${styleName}"` : '';
  return String(text ?? '')
    .split('\n')
    .map((line) => `    <text:p${style}>${xmlEscape(line)}</text:p>`)
    .join('\n');
}

/**
 * Build the FODT document for a draft.
 * @param draft   { title, sections: [{ heading, body, evidenceIds }] }
 * @param resolveEvidence (id) => evidence object or null
 */
export function buildFodt(draft, resolveEvidence) {
  const date = new Date().toISOString().slice(0, 10);
  const parts = [];

  parts.push(`<?xml version="1.0" encoding="UTF-8"?>
<office:document xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"
 xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0"
 xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0"
 xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0"
 office:version="1.2" office:mimetype="application/vnd.oasis.opendocument.text">
  <office:automatic-styles>
    <style:style style:name="Title" style:family="paragraph"><style:text-properties fo:font-size="24pt" fo:font-weight="bold"/></style:style>
    <style:style style:name="H1" style:family="paragraph"><style:text-properties fo:font-size="16pt" fo:font-weight="bold"/></style:style>
    <style:style style:name="H2" style:family="paragraph"><style:text-properties fo:font-size="13pt" fo:font-weight="bold"/></style:style>
    <style:style style:name="Mono" style:family="paragraph"><style:text-properties style:font-name="Consolas" fo:font-size="9pt"/></style:style>
  </office:automatic-styles>
  <office:body><office:text>
    <text:p text:style-name="Title">${xmlEscape(draft.title || 'Untitled report')}</text:p>
    <text:p>Generated by Papers 3 — Repository Research on ${xmlEscape(date)}</text:p>`);

  const referencedIds = [];
  for (const section of draft.sections || []) {
    parts.push(`    <text:p text:style-name="H1">${xmlEscape(section.heading || 'Untitled section')}</text:p>`);
    parts.push(paragraphs(section.body || '', null));
    for (const id of section.evidenceIds || []) {
      if (!referencedIds.includes(id)) referencedIds.push(id);
    }
  }

  parts.push('    <text:p text:style-name="H1">Evidence appendix</text:p>');
  if (referencedIds.length === 0) {
    parts.push('    <text:p>No evidence attached to this draft.</text:p>');
  }
  for (const id of referencedIds) {
    const ev = resolveEvidence(id);
    if (!ev) {
      parts.push('    <text:p text:style-name="H2">(missing evidence)</text:p>');
      parts.push(`    <text:p text:style-name="Mono">evidence ${xmlEscape(id)} no longer exists</text:p>`);
      continue;
    }
    const p = ev.provenance || {};
    const prov = `${p.repoName ?? ''} ${p.filePath ?? ''}@${p.commit ?? ''} lines ${p.startLine ?? '?'}–${p.endLine ?? '?'} sha256 ${p.contentHash ?? ''}`;
    parts.push(`    <text:p text:style-name="H2">${xmlEscape(ev.title || 'Untitled evidence')}</text:p>`);
    parts.push(`    <text:p text:style-name="Mono">${xmlEscape(prov)}</text:p>`);
    parts.push(paragraphs(ev.excerpt || '', 'Mono'));
  }

  parts.push('  </office:text></office:body>\n</office:document>');
  return parts.join('\n');
}

/** File-name slug from a title: lowercase, [a-z0-9-], fallback "report". */
export function slugify(title) {
  const slug = String(title ?? '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
  return slug || 'report';
}
